stages:
  load_data:
    cmd: python src/load_and_save.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_and_save.py
    - data_given_by_client/thyroidDF.csv
    outs:
    - data/raw/thyroidDF.csv
  data_validation:
    cmd: python src/raw_data_validation.py
    deps:
    - src/raw_data_validation.py
    - src/get_data.py
    - data/raw/thyroidDF.csv
  data_preprocess1:
    cmd: python src/data_preprocessing_part1.py
    deps:
    - src/data_preprocessing_part1.py
    - src/get_data.py
    - data/raw/thyroidDF.csv
    outs:
    - data/processed/thyroidDF.csv
  data_preprocess2_and_model_training:
    cmd: python src/data_preprocessing_part2_and_model_training.py --config=params.yaml
    deps: 
    - src/data_preprocessing_part2_and_model_training.py
    - src/get_data.py
    - data/processed/thyroidDF.csv
    outs:
    - models/model.joblib
    - reports/metrics.json
