General:
  list_of_columns_to_remove:
  - patient_id 
  - TSH_measured 
  - T3_measured 
  - TT4_measured 
  - T4U_measured
  - FTI_measured 
  - TBG_measured 
  random_state: 123
  test_size: 0.3


data_location:
  data_given_by_client: data_given_by_client/thyroidDF.csv
  raw_data: data/raw/thyroidDF.csv
  data_after_preprocess_part1: data/processed/thyroidDF.csv

model:
  model_foldername: models
  model_name: model.joblib

